package iesac.pda.HelloApp;

/**
* HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* martes 28 de febrero de 2023 00H07' CST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public iesac.pda.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (iesac.pda.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = iesac.pda.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    iesac.pda.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return iesac.pda.HelloApp.HelloHelper.type ();
  }

}
